### ISSUE TITLE
Checklist for Ember 1.13+ (Glimmer) Support and usurping ember-list-view

### ISSUE THREAD

**Issue by mansona** [emberjs/ember-collection#5]
I am creating this as per the discussions that are found on this thread: https://github.com/emberjs/list-view/issues/245#issuecomment-131170337 if anyone wants me to add anything to the checklist just comment and I will do my best to keep up with what needs to be done.

### Documentation: 
- [ ] update readme to reflect the reason for the new change
- [ ] document new features in the new implementation i.e. cell-layout
- [ ] document the upgrade path for people using ember-list-view

### Implementation: 
- [ ] upgrade tests and make sure they are all passing
- [ ] ???

### Release: 
- [ ] Release first beta version so people can test the current implementation
- [ ] decide if we are releasing a 1.13 release version in line with the new "same version" policy in ember

**Comment by mmun** [comment]
We've decided to commit to supporting 1.13. In particular, we will backport fixes to 1.13 if necessary (or inline the fix if its minor).

**Comment by raytiley** [comment]
I just submitted a PR to the list-view README to point to ember-collection. https://github.com/emberjs/list-view/pull/252

**Comment by calebrosario** [comment]
Do we have an ETA as to when this will be released?

**Comment by rwjblue** [comment]
Yep. It will be released very shortly after it is ready. :smiley_cat:

**Comment by calebrosario** [comment]
Any updates?

**Comment by spinlock99** [comment]
@mansona I'd love to start working on the documentation. If you -- and hopefully others -- are willing to answer lots of noob questions, I'll write them into the documentation so you don't have to answer them twice :-)

**Comment by tschoartschi** [comment]
@rwjblue first of all, thanks for your efforts and your awesome contributions to open source projects. I wanted to ask if there are any updates and when ```ember-collection``` is ready? Right now I would need such functionality and I question myself if I should wait or if I should implement a solution myself

**Comment by mansona** [comment]
"ready" can sometimes be such a strong word :joy: I'm currently using this and it is working fine for me, the real thing it's lacking is documentation. I figured out what I needed it to do from the source and I reckon fresh eyes with a day of hacking at the source and trying to get it to work for a few use cases could come up with some seriously nice documentation. I, unfortunately, cannot commit to this right now

**Comment by tschoartschi** [comment]
@mansona you are right, the word "ready" can be missleading. I just asked because the last release was on 15.9.2015 and has alpha in the version name (```v1.0.0-alpha.4```). I'm always a little bit cautious when using an alpha version in a production app. But I'll give it a quick try and see how it behaves.
